## Tensors

Tensors are data structures just like arrays with some benefits like they can be run on GPU

In [1]:
import torch
import numpy as np

In [2]:
## creating tensor when data is given
data = [[1, 2], [3, 4]]
t1 = torch.tensor(data)
print(f"Shape of this tensor : {t1.shape}")
print(f"Dimensions of this tensor : {t1.ndim}")

Shape of this tensor : torch.Size([2, 2])
Dimensions of this tensor : 2


In [5]:
## creating tensor from a numpy array
ar1 = np.array([1, 2, 3, 4])
print(f"Shape of array : {ar1.shape}")

t2 = torch.from_numpy(ar1)
print(f"Shape of tensor is : {t2.shape}")

Shape of array : (4,)
Shape of tensor is : torch.Size([4])


In [7]:
## converting tensor to numpy array
ar2 = t2.numpy()
print(type(ar2))
print(ar2)

<class 'numpy.ndarray'>
[1 2 3 4]


In [9]:
## retaining property of other tensor in this case we'll use t1
t_zeros = torch.zeros_like(t1)
t_ones = torch.ones_like(t1)
t_rand = torch.rand_like(t1, dtype=torch.float32)

print(f"Zero tensor : {t_zeros}")
print(f"Ones tensor : {t_ones}")
print(f"Rand tensor : {t_rand}")

Zero tensor : tensor([[0, 0],
        [0, 0]])
Ones tensor : tensor([[1, 1],
        [1, 1]])
Rand tensor : tensor([[0.5915, 0.6066],
        [0.6605, 0.6912]])


In [13]:
## making a new tensor by defining shape and data type
shape = (1, 3)
d_type = torch.float32

t4 = torch.rand(shape, dtype=torch.float32)
t5 = torch.ones(shape, dtype=d_type)
t6 = torch.zeros(shape, dtype=d_type)

print(f"t4 : {t4}, Shape : {t4.shape}")
print(f"t5 : {t5}, Shape : {t5.shape}")
print(f"t6 : {t6}, Shape : {t6.shape}")

t4 : tensor([[0.1519, 0.5293, 0.7064]]), Shape : torch.Size([1, 3])
t5 : tensor([[1., 1., 1.]]), Shape : torch.Size([1, 3])
t6 : tensor([[0., 0., 0.]]), Shape : torch.Size([1, 3])


In [18]:
## Device on which tensor are formed
print(f"Device on which tensor are running : {t5.device}")

Device on which tensor are running : cpu


In [19]:
## setting up the device
if torch.cuda.is_available():
    device = "cuda"
else:
    device = "cpu"

print(f"Device in use is : {device}")

Device in use is : cpu


In [21]:
## shifting the tensor to a gpu or etc...
t5.to(device)

tensor([[1., 1., 1.]])

In [ ]:
## concating two or more tensors
shape = (2, 2)
t1 = torch.zeros(shape)
t2 = torch.ones(shape)
t3 = torch.ones(shape)*2

print(f"t1 : {t1}")
print(f"t2 : {t2}")
print(f"t3 : {t3}")

concat_tensor_dim1 = torch.concat([t1, t2, t3], dim=1) ## dim = 1 means concating horizontally
concat_tensor_dim0 = torch.concat([t1, t2, t3], dim=0) ## dim = 0 means concating vertically

print(f"Dim1 : {concat_tensor_dim1}")
print(f"Dim0 : {concat_tensor_dim0}")

t1 : tensor([[0., 0.],
        [0., 0.]])
t2 : tensor([[1., 1.],
        [1., 1.]])
t3 : tensor([[2., 2.],
        [2., 2.]])
Dim1 : tensor([[0., 0., 1., 1., 2., 2.],
        [0., 0., 1., 1., 2., 2.]])
Dim0 : tensor([[0., 0.],
        [0., 0.],
        [1., 1.],
        [1., 1.],
        [2., 2.],
        [2., 2.]])


## Arithematic Operations on Tensors

In [27]:
## lets make two tensors
t1 = torch.rand(size=(2, 2))
t2 = torch.rand(size=(2, 2))

print(f"t1 : {t1}")
print(f"t2 : {t2}")

t1 : tensor([[0.1041, 0.2628],
        [0.2158, 0.6725]])
t2 : tensor([[0.6694, 0.7609],
        [0.2886, 0.3603]])


In [28]:
## Additon and subtraction
add = t1 + t2
sub = t1 - t2

print(f"Addition : {add}")
print(f"Subtract : {sub}")

Addition : tensor([[0.7735, 1.0237],
        [0.5044, 1.0327]])
Subtract : tensor([[-0.5653, -0.4982],
        [-0.0728,  0.3122]])


In [32]:
## multiplication (element-wise)
mult = t1 * t2
## or we can also do by using 'mul' operation
mult2 = t1.mul(t2)

print(f"Mult1 : {mult}")
print(f"Mult2 : {mult2}")

Mult1 : tensor([[0.0697, 0.2000],
        [0.0623, 0.2423]])
Mult2 : tensor([[0.0697, 0.2000],
        [0.0623, 0.2423]])


In [33]:
## we can also define multiplication by defining output tensor
t_out = torch.rand_like(t1)

torch.mul(t1, t2, out=t_out)
print(t_out)

tensor([[0.0697, 0.2000],
        [0.0623, 0.2423]])


### Matrix Multiplication

In [37]:
t1 = torch.rand(size=(2, 2))
t2 = torch.rand(size=(3, 2))

print(f"t1 : {t1}")
print(f"t2 : {t2}")

t1 : tensor([[0.0688, 0.9524],
        [0.7339, 0.2042]])
t2 : tensor([[0.6247, 0.0640],
        [0.5284, 0.2387],
        [0.8289, 0.7245]])


In [39]:
## matrix multiplication ways
m1 = t1 @ t2.T
m2 = t1.matmul(t2.T)
print(f"m1 : {m1}")
print(f"m2 : {m2}")

m1 : tensor([[0.1040, 0.2637, 0.7471],
        [0.4716, 0.4365, 0.7563]])
m2 : tensor([[0.1040, 0.2637, 0.7471],
        [0.4716, 0.4365, 0.7563]])


In [41]:
## we can also do matrix multiplication by defining output tensor
t_out = torch.rand(size=(2, 3))
torch.matmul(t1, t2.T, out=t_out)

tensor([[0.1040, 0.2637, 0.7471],
        [0.4716, 0.4365, 0.7563]])